<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="Ligature.Provisioning.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Platform\Ligature.Platform.Persistence\Ligature.Platform.Persistence.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Ligature.Provisioning</RootNamespace>
    <AssemblyName>Ligature.Provisioning</AssemblyName>
  </PropertyGroup>

</Project>
