// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net;
using Ligature.Platform.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ligature.Platform.Persistence.Migrations
{
    [DbContext(typeof(LigatureDbContext))]
    [Migration("20260911102231_AddUserManagementImmutabilityTriggers")]
    partial class AddUserManagementImmutabilityTriggers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ligature.Platform.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("NotSentReason")
                        .HasColumnType("varchar")
                        .HasColumnName("not_sent_reason");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("notification_type");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("recipient");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("status");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<string>("TransportMessageId")
                        .HasColumnType("varchar")
                        .HasColumnName("transport_message_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenId")
                        .IsUnique()
                        .HasDatabaseName("ux_notification_token_id");

                    b.ToTable("notification", null, t =>
                        {
                            t.HasCheckConstraint("ck_notification_attempted_at_shape", "((\"attempted_at\" IS NOT NULL) IS NOT DISTINCT FROM (\"status\" = 'Sent' OR COALESCE(\"not_sent_reason\" IN ('TokenNotLive', 'SubjectInactive', 'TransportFailed'), false)))");

                            t.HasCheckConstraint("ck_notification_closed_at_iff_terminal", "((\"status\" <> 'Pending') IS NOT DISTINCT FROM (\"closed_at\" IS NOT NULL))");

                            t.HasCheckConstraint("ck_notification_message_id_only_when_sent", "(\"status\" = 'Sent' OR \"transport_message_id\" IS NULL)");

                            t.HasCheckConstraint("ck_notification_not_sent_reason", "\"not_sent_reason\" IN ('TokenNotLive', 'SubjectInactive', 'TransportFailed', 'Abandoned')");

                            t.HasCheckConstraint("ck_notification_reason_iff_not_sent", "((\"status\" = 'NotSent') IS NOT DISTINCT FROM (\"not_sent_reason\" IS NOT NULL))");

                            t.HasCheckConstraint("ck_notification_status", "\"status\" IN ('Pending', 'Sent', 'NotSent')");

                            t.HasCheckConstraint("ck_notification_type", "\"notification_type\" IN ('AccountActivation', 'PasswordReset', 'AdminPasswordReset')");
                        });
                });

            modelBuilder.Entity("Ligature.Platform.Domain.Users.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempt_count");

                    b.Property<string>("IdentityType")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("identity_type");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("PasswordAlgorithm")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("password_algorithm");

                    b.Property<DateTimeOffset>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("UserIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_identity_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UserIdentityId", "IdentityType");

                    b.ToTable("credential", (string)null);
                });

            modelBuilder.Entity("Ligature.Platform.Domain.Users.PasswordHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordAlgorithm")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("password_algorithm");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("UserIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_identity_id");

                    b.HasKey("Id");

                    b.HasIndex("UserIdentityId");

                    b.ToTable("password_history", (string)null);
                });

            modelBuilder.Entity("Ligature.Platform.Domain.Users.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("action");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresHumanActor")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_human_actor");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("resource");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.ToTable("permission", (string)null);
                });

            modelBuilder.Entity("Ligature.Platform.Domain.Users.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("Ligature.Platform.Domain.Users.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("GrantedBy");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RevokedBy");

                    b.HasIndex("RoleId");

                    b.ToTable("role_permission", null, t =>
                        {
                            t.HasCheckConstraint("ck_role_permission_revocation_pair", "(\"revoked_at\" IS NULL) = (\"revoked_by\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Ligature.Platform.Domain.Users.SecurityPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("policy_version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Settings", "Ligature.Platform.Domain.Users.SecurityPolicy.Settings#SecurityPolicySettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeSpan>("ActivationTokenLifetime")
                                .HasColumnType("interval")
                                .HasColumnName("activation_token_lifetime");

                            b1.Property<TimeSpan>("LockoutDuration")
                                .HasColumnType("interval")
                                .HasColumnName("lockout_duration");

                            b1.Property<int>("MaxFailedLoginAttempts")
                                .HasColumnType("integer")
                                .HasColumnName("max_failed_login_attempts");

                            b1.Property<int>("PasswordHistoryDepth")
                                .HasColumnType("integer")
                                .HasColumnName("password_history_depth");

                            b1.Property<int>("PasswordMinLength")
                                .HasColumnType("integer")
                                .HasColumnName("password_min_length");

                            b1.Property<TimeSpan>("PasswordResetTokenLifetime")
                                .HasColumnType("interval")
                                .HasColumnName("password_reset_token_lifetime");

                            b1.Property<TimeSpan>("SessionAbsoluteTimeout")
                                .HasColumnType("interval")
                                .HasColumnName("session_absolute_timeout");

                            b1.Property<TimeSpan>("SessionIdleTimeout")
                                .HasColumnType("interval")
                                .HasColumnName("session_idle_timeout");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EffectiveFrom")
                        .IsUnique();

                    b.HasIndex("PolicyVersion")
                        .IsUnique();

                    b.ToTable("security_policy", (string)null);
                });

            modelBuilder.Entity("Ligature.Platform.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("actor_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("varchar")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar")
                        .HasColumnName("last_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Deactivation", "Ligature.Platform.Domain.Users.User.Deactivation#DeactivationStamp", b1 =>
                        {
                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deactivated_at");

                            b1.Property<Guid>("By")
                                .HasColumnType("uuid")
                                .HasColumnName("deactivated_by");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Id", "ActorType")
                        .IsUnique()
                        .HasDatabaseName("ux_app_user_id_actor_type");

                    b.ToTable("app_user", null, t =>
                        {
                            t.HasCheckConstraint("ck_app_user_actor_type", "\"actor_type\" IN ('Human', 'Agent', 'System')");

                            t.HasCheckConstraint("ck_app_user_deactivation_pair", "(\"deactivated_at\" IS NULL) = (\"deactivated_by\" IS NULL)");

                            t.HasCheckConstraint("ck_app_user_email_no_control_characters", "\"email\" IS NULL OR \"email\" !~ '[\\x00-\\x1F\\x7F-\\x9F]'");

                            t.HasCheckConstraint("ck_app_user_human_names", "\"actor_type\" <> 'Human' OR (\"first_name\" IS NOT NULL AND \"last_name\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_app_user_status", "\"status\" IN ('Active', 'Inactive')");

                            t.HasCheckConstraint("ck_app_user_system_not_deactivated", "\"actor_type\" <> 'System' OR \"deactivated_at\" IS NULL");
                        });
                });

            modelBuilder.Entity("Ligature.Platform.Domain.Users.UserIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("actor_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("IdentityProvider")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("identity_provider");

                    b.Property<string>("IdentityType")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("identity_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("status");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasColumnType("varchar")
                        .HasColumnName("username");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Deactivation", "Ligature.Platform.Domain.Users.UserIdentity.Deactivation#DeactivationStamp", b1 =>
                        {
                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deactivated_at");

                            b1.Property<Guid>("By")
                                .HasColumnType("uuid")
                                .HasColumnName("deactivated_by");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("IdentityProvider", "SubjectId")
                        .IsUnique();

                    b.HasIndex("UserId", "ActorType");

                    b.ToTable("user_identity", (string)null);
                });

            modelBuilder.Entity("Ligature.Platform.Domain.Users.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("actor_type");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<string>("AssignmentReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assignment_reason");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to");

                    b.Property<string>("RevocationReason")
                        .HasColumnType("text")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("RevokedBy");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "ActorType");

                    b.ToTable("user_role", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_role_actor_type", "\"actor_type\" IN ('Human', 'Agent', 'System')");

                            t.HasCheckConstraint("ck_user_role_agent_finite", "\"actor_type\" <> 'Agent' OR \"effective_to\" IS NOT NULL");

                            t.HasCheckConstraint("ck_user_role_effective_period", "\"effective_to\" IS NULL OR \"effective_to\" > \"effective_from\"");

                            t.HasCheckConstraint("ck_user_role_revocation_pair", "(\"revoked_at\" IS NULL) = (\"revoked_by\" IS NULL)");

                            t.HasCheckConstraint("ck_user_role_revocation_reason", "\"revoked_at\" IS NULL OR \"revocation_reason\" IS NOT NULL");

                            t.HasCheckConstraint("ck_user_role_scope", "(\"scope_type\" = 'Global' AND \"scope_id\" IS NULL) OR (\"scope_type\" <> 'Global' AND \"scope_id\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Ligature.Platform.Domain.Users.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("RevocationReason")
                        .HasColumnType("text")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_identity_id");

                    b.HasKey("Id");

                    b.HasIndex("RevokedBy");

                    b.HasIndex("UserIdentityId");

                    b.ToTable("user_session", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_session_expires_at", "\"expires_at\" > \"created_at\"");

                            t.HasCheckConstraint("ck_user_session_last_activity_at", "\"last_activity_at\" >= \"created_at\"");

                            t.HasCheckConstraint("ck_user_session_revocation_pair", "(\"revoked_at\" IS NULL) = (\"revoked_by\" IS NULL)");

                            t.HasCheckConstraint("ck_user_session_revocation_reason", "\"revoked_at\" IS NULL OR \"revocation_reason\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Ligature.Platform.Domain.Users.UserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("InvalidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invalidated_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("token_hash");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("token_type");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_identity_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UserIdentityId");

                    b.ToTable("user_token", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_token_expires_after_created", "\"expires_at\" > \"created_at\"");

                            t.HasCheckConstraint("ck_user_token_not_used_and_invalidated", "NOT (\"used_at\" IS NOT NULL AND \"invalidated_at\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_user_token_token_type", "\"token_type\" IN ('Activation', 'PasswordReset')");
                        });
                });

            modelBuilder.Entity("Ligature.Platform.Domain.Notifications.Notification", b =>
                {
                    b.HasOne("Ligature.Platform.Domain.Users.UserToken", null)
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ligature.Platform.Domain.Users.Credential", b =>
                {
                    b.HasOne("Ligature.Platform.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ligature.Platform.Domain.Users.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserIdentityId", "IdentityType")
                        .HasPrincipalKey("Id", "IdentityType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ligature.Platform.Domain.Users.PasswordHistory", b =>
                {
                    b.HasOne("Ligature.Platform.Domain.Users.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserIdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ligature.Platform.Domain.Users.Permission", b =>
                {
                    b.HasOne("Ligature.Platform.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ligature.Platform.Domain.Users.Role", b =>
                {
                    b.HasOne("Ligature.Platform.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ligature.Platform.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ligature.Platform.Domain.Users.RolePermission", b =>
                {
                    b.HasOne("Ligature.Platform.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("GrantedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ligature.Platform.Domain.Users.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ligature.Platform.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("RevokedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ligature.Platform.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ligature.Platform.Domain.Users.SecurityPolicy", b =>
                {
                    b.HasOne("Ligature.Platform.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ligature.Platform.Domain.Users.User", b =>
                {
                    b.HasOne("Ligature.Platform.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ligature.Platform.Domain.Users.UserIdentity", b =>
                {
                    b.HasOne("Ligature.Platform.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ligature.Platform.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId", "ActorType")
                        .HasPrincipalKey("Id", "ActorType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ligature.Platform.Domain.Users.UserRole", b =>
                {
                    b.HasOne("Ligature.Platform.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ligature.Platform.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("RevokedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ligature.Platform.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ligature.Platform.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId", "ActorType")
                        .HasPrincipalKey("Id", "ActorType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ligature.Platform.Domain.Users.UserSession", b =>
                {
                    b.HasOne("Ligature.Platform.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("RevokedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ligature.Platform.Domain.Users.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserIdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ligature.Platform.Domain.Users.UserToken", b =>
                {
                    b.HasOne("Ligature.Platform.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ligature.Platform.Domain.Users.UserIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserIdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
